// Generated by CoffeeScript 2.2.3
(function() {
    // Marketplace Client's public blockchain

  var Blockchain, Storage;

  Storage = require("./storage");

  Blockchain = class Blockchain extends Storage {
    constructor(root) {
      super(root + "/public");
    }

  };

  module.exports = Blockchain;

}).call(this);
