// Generated by CoffeeScript 2.2.3
(function() {
    // Marketplace Client's private ledger

  var Ledger, Storage;

  Storage = require("./storage");

  Ledger = class Ledger extends Storage {
    constructor(root) {
      super(root + "/private");
    }

  };

  module.exports = Ledger;

}).call(this);
